### PR TITLE
fix: better defaults to to-image

### PR DESCRIPTION
**Pull request by hugosenari**
As mentioned in #3 
- better defaults
  -  genix.json like as default
  - reasonable camera posion/angle
- better arg names
- better arg values
- image size arg

~Now the only missing part would be transparent background :thinking:~

edit: Converted export-color-svg.sh to nu and embeded in to-image.nu (same for png and svg)

### CODE REVIEW

**Comment by hugosenari** [comment]
Should I change README to document it?

**Comment by cab404** [comment]
> Should I change README to document it?

Eeh, if you really want to :)

> Now the only missing part would be transparent background 🤔

We can implement this via SVG export

**Comment by hugosenari** [comment]
> Eeh, if you really want to :)

Done

> We can implement this via SVG export

SVG export is just. 

```sh
nix run .#to-image -- bla.svg
```

But it export it without colors :thinking: 

```xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="182mm" height="182mm" viewBox="-91 -91 182 182" xmlns="http://www.w3.org/2000/svg" version="1.1">
<title>OpenSCAD Model</title>
<path d="
M 9.56625,-58.2207 L 1.09389,-60.4909 L -6.81458,-90.0057 L -25.4516,-82.286 L -21.2132,-66.468 L -46.9748,-73.3708
 L -53.9726,-70.4722 L -57.9555,-55.6076 L 23.7084,-33.7258 z
M 47.9326,-34.4039 L 43.547,-42 L 58.825,-68.4623 L 40.188,-76.182 L 32,-62 L 18.6648,-85.0972
 L 11.667,-87.9958 L -1.66025,-80.3013 L 40.6121,-7.08337 z
M -7.08337,-40.6121 L -34.4039,-47.9326 L -42,-43.547 L -68.4623,-58.825 L -76.182,-40.188 L -62,-32
 L -85.0972,-18.6648 L -87.9958,-11.667 L -80.3013,1.66025 z
M 58.2207,9.56625 L 60.4909,1.09389 L 90.0057,-6.81458 L 82.286,-25.4516 L 66.468,-21.2132 L 73.3708,-46.9748
 L 70.4722,-53.9726 L 55.6076,-57.9555 L 33.7258,23.7084 z
M -33.7258,-23.7084 L -58.2207,-9.56625 L -60.4909,-1.09389 L -90.0057,6.81458 L -82.286,25.4516 L -66.468,21.2132
 L -73.3708,46.9748 L -70.4722,53.9726 L -55.6076,57.9555 z
M 76.182,40.188 L 62,32 L 85.0972,18.6648 L 87.9958,11.667 L 80.3013,-1.66025 L 7.08337,40.6121
 L 34.4039,47.9326 L 42,43.547 L 68.4623,58.825 z
M 1.66025,80.3013 L -40.6121,7.08337 L -47.9326,34.4039 L -43.547,42 L -58.825,68.4623 L -40.188,76.182
 L -32,62 L -18.6648,85.0972 L -11.667,87.9958 z
M 25.4516,82.286 L 21.2132,66.468 L 46.9748,73.3708 L 53.9726,70.4722 L 57.9555,55.6076 L -23.7084,33.7258
 L -9.56625,58.2207 L -1.09389,60.4909 L 6.81458,90.0057 z
" stroke="black" fill="lightgray" stroke-width="0.5"/>
</svg>
```

**Comment by hugosenari** [comment]
[README preview](https://github.com/cruel-intentions/genix7000/tree/to-image-better-default)

**Comment by cab404** [comment]
> But it export it without colors 🤔

There is a [script](https://github.com/cab404/genix7000/blob/master/export-color-svg.sh) for that?

**Comment by hugosenari** [comment]
> > But it export it without colors 🤔
> 
> There is a [script](https://github.com/cab404/genix7000/blob/master/export-color-svg.sh) for that?

Adapted ;-)

**Comment by cab404** [comment]
@ofborg jk

**Pull request merged**
